### ISSUE TITLE
How to create a production build? How to deploy?

### ISSUE THREAD

**Issue by deltaidea** [deltaidea/golad#8]
@lucky-ly

**Comment by lucky-ly** [comment]
Create production build:
`cd WebApi`
`dotnet restore`
'npm install'
`dotnet publish`

Default output folder is `./bin/Debug/netcoreapp1.1/publish`

More info about publish command [here](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-publish)

**Comment by deltaidea** [comment]
We should add that to README.

**Comment by lucky-ly** [comment]
As part of **Quickstart** or in its own section?

**Comment by deltaidea** [comment]
Separately.
